name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: sashaperekhrest
          password: Sasha548gtr

      - name: Install dependecies
        run: npm ci

      - name: Build and push Docker images
        run: |
          docker-compose -f test_api/docker-compose.yml build
          docker-compose -f test_api/docker-compose.yml push
